// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type SchemaMigration struct {
	Version string
}

type Todo struct {
	ID          int64
	Title       string
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	CreatedAt   sql.NullTime
}
