// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const changeStatus = `-- name: ChangeStatus :one
UPDATE todos
SET completed = ?
WHERE id = ?
RETURNING id, title, completed, completed_at, created_at
`

type ChangeStatusParams struct {
	Completed sql.NullBool
	ID        int64
}

func (q *Queries) ChangeStatus(ctx context.Context, arg ChangeStatusParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, changeStatus, arg.Completed, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const create = `-- name: Create :one
INSERT INTO todos (
    title
) VALUES (?)
RETURNING id, title, completed, completed_at, created_at
`

func (q *Queries) Create(ctx context.Context, title string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, create, title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const readAll = `-- name: ReadAll :many
SELECT id, title, completed, completed_at, created_at FROM todos
ORDER BY completed ASC, created_at ASC
`

func (q *Queries) ReadAll(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, readAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readOne = `-- name: ReadOne :one
SELECT id, title, completed, completed_at, created_at FROM todos
WHERE id = ?
`

func (q *Queries) ReadOne(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, readOne, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
