package cli

import (
	_ "embed"
	"log"
	"os"
	"path/filepath"
)

// NOTE: this file will be generated by dbmate before build
//
//go:embed assets/generated/todos.db
var emptyDB []byte

const appDir string = "todo"
const dbName string = "todos.db"

var DBURI string

func init() {
	configDir, err := os.UserConfigDir()

	if err != nil {
		log.Panicf("Can't access user's config dir, %v", err)
	}

	appStateDir := filepath.Join(configDir, appDir)

	if err := os.MkdirAll(appStateDir, 0755); err != nil {
		log.Panicf("Can't create app state directory, %v", err)
	}

	dbPath := filepath.Join(appStateDir, dbName)

	dbPathStat, err := os.Stat(dbPath)

	if err != nil {
		if os.IsNotExist(err) {
			if err := os.WriteFile(dbPath, emptyDB, 0644); err != nil {
				log.Panicf("Can't create database file, %v", err)
			}
		} else if dbPathStat.IsDir() {
			log.Panicln("Database file is a directory")
		} else {
			log.Panicf("Error reading db file, %v", err)
		}
	}

	DBURI = dbPath
}
